### ISSUE TITLE
1 is also shown as a prime number.

### ISSUE THREAD

**Issue by thakursaurabh1998** [ayusin51/Acadview#1]
https://github.com/ayusin51/Acadview/blob/67f14c44dd776bbedc8f2c9b95f0ee62ddf98883/Assignment-3/PrimeNum.java#L6

`checkPrime` function returns true if I enter `1`.
That's a wrong output.
1 is not a prime number.
@ayusin51

**Comment by ayusin51** [comment]
Thanks for your kind help.

**Comment by thakursaurabh1998** [comment]
No problem :smile:
